# Generated by Django 2.2.28 on 2022-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=False, max_digits=5)),
                ('Mfg_date', models.DateField(blank=True, null=True)),
                ('Exp_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
